Problem Statement 1:
In each of the following situations, state whether it is a correctly stated hypothesis
testing problem and why?
1. 𝐻0: 𝜇 = 25, 𝐻1: 𝜇 ≠ 25
2. 𝐻0: 𝜎 > 10, 𝐻1: 𝜎 = 10
3. 𝐻0: 𝑥 = 50, 𝐻1: 𝑥 ≠ 50
4. 𝐻0: 𝑝 = 0.1, 𝐻1: 𝑝 = 0.5
5. 𝐻0: 𝑠 = 30, 𝐻1: 𝑠 > 30

In [1]:
print("1. 𝐻0: 𝜇 = 25, 𝐻1: 𝜇 ≠ 25: It is correct. mu is a  population parameter. Null hypothesis contains equal sign. Alternate hypothesis contains not equal sign.\n")
print("2. 𝐻0: 𝜎 > 10, 𝐻1: 𝜎 = 10, It is wrong. It tells about population parameter but Null hypothesis does not contain equal sign rather alternate hypothesis contains equal sign.\n")
print("3. 𝐻0: 𝑥 = 50, 𝐻1: 𝑥 ≠ 50, It is wrong, becuase x is not a population parameter. \n")
print("4. 𝐻0: 𝑝 = 0.1, 𝐻1: 𝑝 = 0.5 It is wrong because alternate hypothesis contains equal sign.\n")
print("5. 𝐻0: 𝑠 = 30, 𝐻1: 𝑠 > 30 It is wrong because s is not population parameter.")

1. 𝐻0: 𝜇 = 25, 𝐻1: 𝜇 ≠ 25: It is correct. mu is a  population parameter. Null hypothesis contains equal sign. Alternate hypothesis contains not equal sign.

2. 𝐻0: 𝜎 > 10, 𝐻1: 𝜎 = 10, It is wrong. It tells about population parameter but Null hypothesis does not contain equal sign rather alternate hypothesis contains equal sign.

3. 𝐻0: 𝑥 = 50, 𝐻1: 𝑥 ≠ 50, It is wrong, becuase x is not a population parameter. 

4. 𝐻0: 𝑝 = 0.1, 𝐻1: 𝑝 = 0.5 It is wrong because alternate hypothesis contains equal sign.

5. 𝐻0: 𝑠 = 30, 𝐻1: 𝑠 > 30 It is wrong because s is not population parameter.


Problem Statement 2:
The college bookstore tells prospective students that the average cost of its
textbooks is Rs. 52 with a standard deviation of Rs. 4.50. A group of smart statistics
students thinks that the average cost is higher. To test the bookstore’s claim against
their alternative, the students will select a random sample of size 100. Assume that
the mean from their random sample is Rs. 52.80. Perform a hypothesis test at the
5% level of significance and state your decision.

In [2]:
from scipy import stats
import math

#H0 :  mu = 52 Ha : mu > 52

mu= 52
xbar=52.80
S = 4.50
n = 100
alpha = 0.10
Z = (xbar-mu)/((S)/(math.sqrt(n)))

if (Z < 0):
    p_val = stats.norm.cdf(Z)
else:
    p_val = 1-stats.norm.cdf(Z)
    
print("Z value is :", Z , "and p value is :", p_val)
print("p = 0.0377 < 0.10 therefore we reject the null hypothesis")
print('''There is sufficient evidence to suggest that the population mean is greater than 52,
at the 0.10 significance level''')


Z value is : 1.7777777777777715 and p value is : 0.0377201798134007
p = 0.0377 < 0.10 therefore we reject the null hypothesis
There is sufficient evidence to suggest that the population mean is greater than 52,
at the 0.10 significance level


Problem Statement 3:
A certain chemical pollutant in the Genesee River has been constant for several
years with mean μ = 34 ppm (parts per million) and standard deviation σ = 8 ppm. A
group of factory representatives whose companies discharge liquids into the river is
now claiming that they have lowered the average with improved filtration devices. A
group of environmentalists will test to see if this is true at the 1% level of
significance. Assume \ that their sample of size 50 gives a mean of 32.5 ppm.
Perform a hypothesis test at the 1% level of significance and state your decision.

In [130]:
from scipy import stats
import math

# H0 = 34 vs H1 <34

mu = 34
S = 8
xbar=32.5
n = 50
alpha = 0.05
Z = (xbar-mu)/((S)/(math.sqrt(n)))
if (Z < 0):
    p_val = stats.norm.cdf(Z)
else:
    p_val = 1-stats.norm.cdf(Z)
    
print("Z value is :", Z , "and p value is :", p_val)
print("Here p value is greater than alpha, therefore we fail to reject the null hypothesis\n")
print("There is insufficient evidence to support the claim.")

Z value is : -1.3258252147247767 and p value is : 0.0924487994828001
Here p value is greater than alpha, therefore we fail to reject the null hypothesis

There is insufficient evidence to support the claim.


Problem Statement 4:
Based on population figures and other general information on the U.S. population,
suppose it has been estimated that, on average, a family of four in the U.S. spends
about $1135 annually on dental expenditures. Suppose further that a regional dental
association wants to test to determine if this figure is accurate for their area of
country. To test this, 22 families of 4 are randomly selected from the population in
that area of the country and a log is kept of the family’s dental expenditure for one
year. The resulting data are given below. Assuming, that dental expenditure is
normally distributed in the population, use the data and an alpha of 0.5 to test the
dental association’s hypothesis.
1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
872, 913, 944, 954, 987, 1695, 995, 1003, 994

In [52]:
import numpy as np
from scipy import stats
import math
import pandas as pd

#H0: mu  = 1135
#H1: mu not equal to 1135


aplha = 0.05
list = [1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
872, 913, 944, 954, 987, 1695, 995, 1003, 994]
n = 22
mu = 1135
xbar = np.mean(list)
print("\nxbar:",(round(xbar,4)))
S = np.std(list)
print("\nStandard deviation :",(round(S,4)))

#Test statistics : xbar-mu /s/rootn

t = (xbar-mu)/((S)/(math.sqrt(n)))
print("\nT calculated:", (round(t,4)))

#pvalue p(tn-1>|tcal|)
#p()

p_value =stats.t.cdf(21, 0.025)

print("\nSince p value is greater than 0.05, we fail to reject null hypothesis:", (round(p_value,4)))
print("\nThere is sufficient evidence to claim the average dental expenditure is 1135")


xbar: 1031.3182

Standard deviation : 234.848

T calculated: -2.0707

Since p value is greater than 0.05, we fail to reject null hypothesis: 0.565

There is sufficient evidence to claim the average dental expenditure is 1135


Problem Statement 5:
In a report prepared by the Economic Research Department of a major bank the
Department manager maintains that the average annual family income on Metropolis
is $48,432. What do you conclude about the validity of the report if a random sample
of 400 families shows and average income of $48,574 with a standard deviation of
2000?

In [5]:
from scipy import stats
import math

#H0: mu = 48432 vs H1: mu not equal to 48432

mu = 48432
n = 400
xbar = 48574
s = 2000
#Assuming alpha = 0.05 where the critical value is 1.96 in a two tail test

#Z test
Z = (xbar-mu)/((s)/(math.sqrt(n)))
print(Z)
print('''Since the test statistics: ", Z ,"is less than 1.96 we do not reject the null hypothesis, 
and hence the report is valid''')


1.42
Since the test statistics: ", Z ,"is less than 1.96 we do not reject the null hypothesis, 
and hence the report is valid


Problem Statement 6:
Suppose that in past years the average price per square foot for warehouses in the
United States has been $32.28. A national real estate investor wants to determine
whether that figure has changed now. The investor hires a researcher who randomly
samples 19 warehouses that are for sale across the United States and finds that the
mean price per square foot is $31.67, with a standard deviation of $1.29. assume
that the prices of warehouse footage are normally distributed in population. If the
researcher uses a 5% level of significance, what statistical conclusion can be
reached? What are the hypotheses?

In [48]:
from scipy import stats
import math
import numpy as np
import pandas as pd
#H0: mu = 32.28,  H1: mu not equal to 32.28
n = 19
xbar = 31.67
mu = 32.28
sd = 1.29
#test statistic z = (xbar - mu)/(s/sqrt(n))

Z = (xbar - mu)/((sd)/(math.sqrt(n)))
print("\nTest statistics:",(round(Z,4)))
#critical value at 95% confidence interval is +/- 1.96
print('''\nSince critical value is greatre than test statistics we accept H0. 
And conclude that the average price per square foot for warehouses in the
United States has NOT CHANGED''')



Test statistics: -2.0612

Since critical value is greatre than test statistics we accept H0. 
And conclude that the average price per square foot for warehouses in the
United States has NOT CHANGED


problem statement 7: Fill in the blank spaces in the table and draw your conclusions from it.

acceptance region.    sample size.   alpha.  beta at mue = 52.   beta at mue= 50.5
48.5<xbar<51.5       10
48<xbar<52.          10
48.81<xbar<51.9.     16
48.42<xbar<51.58.    16

In [138]:
from scipy import stats
import math
from numpy.random import randn
import numpy as np


In [144]:
import pandas as pd 

In [150]:
list = [[48.5,50,.79],[51.5,50,.79],[48,50,.79],[52,50,.79],[48.81,50,.625],[51.9,50,.625],[48.42,50,.625],[51.58,50,.625]]
a = []

for i in list:
    x =  i[0] 
    mu = i[1] 
    SEM =i[2]
    z = (x - mu)/SEM
    if (z < 0):
        alpha  = stats.norm.cdf(z)
    else:
        alpha = 1-stats.norm.cdf(z)
    a.append(round((alpha),4))


alfa = []
for o in range(0, len(d),2):
    alfa.append(round((d[o]+d[o+1]),4))


list3 = [[51.5,52,.79],[52,52,.79],[51.9,52,.625],[51.58,52,.625]]   
b2 = []
for j in list3:
    xbar = j[0]
    mu2 = j[1]
    s = j[2]
  #  Z2 = (xbar-mu2)/(sigma/np.sqrt(n)
    Z2 = (xbar-mu2)/(s)
    beta = stats.norm.cdf(Z2)
    b2.append(round((beta),4))


list4 = [[51.5,50.5,.79],[52,50.5,.79],[51.9,50.5,.625],[51.58,50.5,.625]]   
b3 = []
for k in list4:
    xbar = k[0]
    mu3 = k[1]
    s = k[2]
    Z3 = (xbar-mu3)/(s)
    beta = stats.norm.cdf(Z3)
    b3.append(round((beta),4))


TI_TII_Er = {
    "Acceptance region": ["48.5<xbar<51.5", "48<xbar<52", "48.81<xbar<51.9","48.42<xbar<51.58"],
    "Sample size" : ["10","10","16","16"],
    "Alpha" : ["0.0576", "0.0114", "0.0297", "0.0114"],
    "Beta at mu = 52":["0.2634", "0.5", "0.4364", "0.2508"],
    "Beta at mu = 50.5":["0.8972", "0.9712", "0.9875", "0.958"]
}

TI_TII_Er_df = pd.DataFrame(TI_TII_Er)
TI_TII_Er_df

Acceptance region Sample size   Alpha Beta at mu = 52 Beta at mu = 50.5
0    48.5<xbar<51.5          10  0.0576          0.2634            0.8972
1        48<xbar<52          10  0.0114             0.5            0.9712
2   48.81<xbar<51.9          16  0.0297          0.4364            0.9875
3  48.42<xbar<51.58          16  0.0114          0.2508             0.958

problem statement 8: Find the t-score for a sample size of 16 taken from a population with mean 10 when
the sample mean is 12 and the sample standard deviation is 1.5.


In [53]:
from scipy import stats
import math

n = 16
mu = 10
xbar = 12
sample_sd = 1.5

t = (xbar-mu)/((sample_sd)/(math.sqrt(n)))
print("t_score:",(round(t,4)) )


t_score: 5.3333


problem statement 9: Problem Statement 9:
Find the t-score below which we can expect 99% of sample means will fall if samples
of size 16 are taken from a normally distributed population.

In [54]:
from scipy import stats
import math

n = 16
#noramlly distributed
t = stats.t.ppf(1-0.01, 15)
print("t_scores:",(round(t,4)))

t_scores: 2.6025


problem statement 10: If a random sample of size 25 drawn from a normal population gives a mean of 60
and a standard deviation of 4, find the range of t-scores where we can expect to find
the middle 95% of all sample means. Compute the probability that (−𝑡0.05 <𝑡<𝑡0.10).


In [31]:
from scipy import stats
import math

# Let all sample mean of 95% lie between x1 and x2, with t score correspoding 
#to left tail at 0.05 significance i,e. -0.025 and 0.025 is t1 and t2.

n = 25
df = n-1
mu = 60
s = 4
alpha = 0.05
t1 = stats.t.ppf(0.025, 24)
t1_score = (round(t1,4))
print("t1 score:", (t1_score))
t2 = stats.t.ppf(1-0.025, 24)
t2_score = (round(t2,4))
print("t2 score:",(round(t2_score,4)))
#therefore the 95% middle range is 
x1 =(t1_score)*(((s)/(math.sqrt(n))))--mu
x2 =(t2_score)*(((s)/(math.sqrt(n))))--mu
print("\nTherefore the 95% middle range is:", x1 ,"and", x2, "respectively")
#Compute the probability that (−𝑡0.05 <𝑡<𝑡0.10).
q = 1-stats.norm.cdf(0.05)
r = stats.norm.cdf(0.1)
print("\nprobabily that (−𝑡0.05 <𝑡<𝑡0.10):", (round(r-q,4)))


t1 score: -2.0639
t2 score: 2.0639

Therefore the 95% middle range is: 58.34888 and 61.65112 respectively

probabily that (−𝑡0.05 <𝑡<𝑡0.10): 0.0598


Problem statement 11: Two-tailed test for difference between two population means Is there evidence to conclude that the number of people travelling from Bangalore to Chennai is different from the number of people travelling from Bangalore to Hosur in a week, given the following: Population 1: Bangalore to Chennai n1 = 1200 x1 = 452 s1 = 212 Population 2: Bangalore to Hosur n2 = 800 x2 = 523 s2 = 185


In [78]:
from scipy import stats
from math import sqrt
from numpy.random import seed
from numpy.random import randn
from numpy import mean
from scipy.stats import sem
from scipy.stats import t
from scipy.stats import ttest_ind

#hypothesis : mu1 = mu2

# for population 1
n1 = 1200
x1bar = 452
s1 = 212
# for population 2
n2 = 800
x2bar = 523
s2 = 185
#stats.ttest_ind(rvs1,rvs2)
t = (x1bar-x2bar)/math.sqrt(((s1**2/n1)+(s2**2/n2)))
print(abs((round(t,4))))
#degrees of freedom
df = (n1 + n2) - 2
alpha = 0.05

print('''\nsince abs(t) is > critical value 1.96, we Reject the null hypothesis, 
and we have enough evidence to conclude that the number of people travelling from
Bangalore to Chennai is different from the number of people travelling from Bangalore
to Hosur in a week,''')


7.9264

since abs(t) is > critical value 1.96, we Reject the null hypothesis, 
and we have enough evidence to conclude that the number of people travelling from
Bangalore to Chennai is different from the number of people travelling from Bangalore
to Hosur in a week,


Problem Statement 12:
Is there evidence to conclude that the number of people preferring Duracell battery is
different from the number of people preferring Energizer battery, given the following:
Population 1: Duracell
n1 = 100
x1 = 308
s1 = 84
Population 2: Energizer
n2 = 100
x2 = 254
s2 = 67

In [86]:
from scipy import stats
import math
from scipy.stats import t

#H0: Number of people using duarcell is equal to number of people using energizer battery: mu1 = mu2
#H1: Number of people using duarcell is not equal to number of people using energizer battery: mu1 not equal to  mu2

n1 = 100
n2 = 100
x1bar = 308
x2bar = 254
s1 = 84
s2 = 67
#S = pooled standard deviation 
S = (math.sqrt(((n1-1)*((s1)**2)+(n2-1)*((s2)**2)) / (n1+n2-2)))
print("\nPooled standard deviation:", (round(S,4)))
#substituting the values for test statistics
test_stat = (x1bar-x2bar) / (S) * (math.sqrt((1/n1)+(1/n2)))
print("\ntest stats:", (round(test_stat,4)))
#degree of freedom  = n1+n2 -2 = 198
print('''\nCritical value at 5% significance at 198 degrees of freedom is 1.97, 
Since calculated value is less than critical value ,\nwe fail to reject null hypothesis,
\nTherefore people preferring Duracell battery is equal to people referring Energizer battery.''')
      
      


Pooled statndard deviation: 75.977

test stats: 0.1005

Critical value at 5% significance at 198 degrees of freedom is 1.97, 
Since calculated value is less than critical value ,
we fail to reject null hypothesis,

Therefore people preferring Duracell battery is equal to people referring Energizer battery.


Problem Statement 13:
Pooled estimate of the population variance
Does the data provide sufficient evidence to conclude that average percentage
increase in the price of sugar differs when it is sold at two different prices?
Population 1: Price of sugar = Rs. 27.50 n1 = 14
x1 = 0.317%
s1 = 0.12%
Population 2: Price of sugar = Rs. 20.00 n2 = 9
x2 = 0.21%
s2 = 0.11%

In [95]:
from scipy import stats
import math
from scipy.stats import t

#H0: mu1 = m2 vs H1: mu1 not equal to mu2
price = 27.50
n_1 = 14
x1_bar = 0.317
s1 = 0.12
price2 = 20
n_2 = 9
x2_bar = 0.21
s2 = 0.11
df = 21
#TEST STATISTICS
#S_square = ((n_1-1)*((s1)**2)+(n_2-1)*((s2)**2)) / (n_1+n_2-2)
S = (math.sqrt(((n_1-1)*((s1)**2)+(n_2-1)*((s2)**2)) / (n_1+n_2-2)))
print("\nPooled standard deviation:",(round(S,4)))

#test_stat = (x1bar-x2bar) / (S) * (math.sqrt((1/n1)+(1/n2)))
t_stat = (x1_bar-x2_bar) / (S) * (math.sqrt((1/n_1)+(1/n_2)))
print("\ntest statistics:",(round(t_stat,4)))

p_value = stats.norm.cdf(t_stat)
print("\np_value",p_value)

print('''\nCritical value at 5% significance at 21  degrees of freedom is 2.08, 
Since calculated value is less than critical value ,\nwe fail to reject null hypothesis,.''')


Pooled standard deviation: 0.1163

test statistics: 0.3931

p_value 0.6528804825865354

Critical value at 5% significance at 21  degrees of freedom is 2.08, 
Since calculated value is less than critical value ,
we fail to reject null hypothesis,.


Problem Statement 14:
The manufacturers of compact disk players want to test whether a small price
reduction is enough to increase sales of their product. Is there evidence that the
small price reduction is enough to increase sales of compact disk players?
Population 1: Before reduction
n1 = 15
x1 = Rs. 6598 s1 = Rs. 844
Population 2: After reduction n2 = 12
x2 = RS. 6870
s2 = Rs. 669

In [27]:
from scipy import stats
import math

#H0: mu2-m1<=0
#H1: mu2-m1>0

#population 1
n1 = 15
x1 = 6598
s1 = 844
#population 2
n2 = 12
x2 = 6870
s2 = 669
df = n1 + n2 - 2
#sigma = s1-s2

S_p = ((n1-1)*((s1)**2)+(n2-1)*((s2)**2)) / (n1+n2-2)
print("\nSp square",S_p)
S = (math.sqrt(S_p))
#print(S)
d = math.sqrt((1/n1)+(1/n2))

t = (x2-x1) / (S*d)
print("\nT calculated",t)

p_value = stats.norm.cdf(t)
print("\np_value",p_value)
print("\nSince p value greater than 0.05 we fail to reject H0, i,e the price reduction does not effect the sales at 0.05.")


Sp square 595835.0

T calculated 0.9098300343990459

p_value 0.8185439237457348

Since p value greater than 0.05 we fail to reject H0, i,e the price reduction does not effect the sales at 0.05.


Problem Statement 15:
Comparisons of two population proportions when the hypothesized difference is zero
Carry out a two-tailed test of the equality of banks’ share of the car loan market in
1980 and 1995.
Population 1: 1980
n1 = 1000
x1 = 53
𝑝 1 = 0.53
Population 2: 1985
n2 = 100
x2 = 43
𝑝 2= 0.53

In [38]:
from scipy import stats
import math

#H0:P1=P2, ,H1:P1 NOT EQUAL TO P2
#population 1

In [58]:
n1 = 100
x1 = 53
p1bar = 0.53
#population 2
n2 = 100
x2 = 43
p2bar = 0.43

#Critical value at 5% alpha is 1.96
#p1bar = x1/n1
#p2bar = x2/n2
#pooled proportion = x1+x2/n1+n2
pp = (x1+x2)/(n1+n2)
qq = 1-pp
z_test = (p1bar-p2bar)/(math.sqrt((pp)*(qq)*(1/n1+1/n2)))
print("\nz_test:",(round(z_test,4)),"Since z_test is less than critical value at 5% (1.96) ,we reject the null hypothesis.")


z_test: 1.4153 Since z_test is less than critical value at 5% (1.96) ,we reject the null hypothesis.


Problem Statement 16:
Carry out a one-tailed test to determine whether the population proportion of
traveler’s check buyers who buy at least $2500 in checks when sweepstakes prizes
are offered as at least 10% higher than the proportion of such buyers when no
sweepstakes are on.
Population 1: With sweepstakes
n1 = 300
x1 = 120
𝑝 = 0.40
Population 2: No sweepstakes n2 = 700
x2 = 140
𝑝 2= 0.20

In [60]:
from scipy import stats
import math

#H0: P1-P2 <= 0.10   Vs    H1: p1-p2 > 0.10
#population 1 with sweepstakes 

n1 = 300
x1 = 120
p1 = 0.40
p1_p2 = 0.10
q1 = 0.60
#population 2 , no sweepstakes
n2 = 700
x2 = 140
p2 = 0.20
q2 = 0.80
#ZTest for two sample  = (p1bar-p2bar)-(p1-p2)/root of (p1bar(1-p1bar/n1))+(p2bar(1-p2bar/n2))
Z = ((p1-p2)-(p1_p2)) / (math.sqrt(((p1)*(q1)/n1)+((p2)*(q2)/n2)))
print("\nZ test:",(round(Z,4)) )
p_value =1- stats.norm.cdf(Z)
print("\np_value",(round(p_value,4)))
print("\nSince pvalue is less than aplha we Reject h0.")


Z test: 3.118

p_value 0.0009

Since pvalue is less than aplha we Reject h0.


Problem Statement 17:
A die is thrown 132 times with the following results: Number turned up: 1, 2, 3, 4, 5, 6
Frequency: 16, 20, 25, 14, 29, 28
Is the die unbiased? Consider the degrees of freedom as 𝑝 − .

In [61]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math
import numpy as np 
import pandas as pd 
from scipy import stats

#H0 : die is unbiased, H1: die is not unbiased

# A die is thrown 132 times

n = 6
dice = {'Number turned on dice':['1','2','3','4','5','6'],
    'observed': [16,'20','25','14','29',28]
        }
df = pd.DataFrame(dice, columns = ['Number turned on dice','observed'], index = ['0', '1','2','3','4','5'])
print(df)

dof = (n-1)

expected = [22, 22, 22, 22, 22, 22]
actual =  [16, 20, 25, 14, 29, 28]
stats.chisquare(actual, expected)

critical = chi2.ppf(.95, 5)
print((round(critical,4)))

print("chi-square calculated is less than chi-square at aplha, there we accept the null hypothesis")
stats.chisquare(actual, expected)

  Number turned on dice observed
0                     1       16
1                     2       20
2                     3       25
3                     4       14
4                     5       29
5                     6       28
11.0705
chi-square calculated is less than chi-square at aplha, there we accept the null hypothesis


Power_divergenceResult(statistic=9.0, pvalue=0.1090641579497725)

Problem Statement 18:
In a certain town, there are about one million eligible voters. A simple random
sample of 10,000 eligible voters was chosen to study the relationship between
gender and participation in the last election. The results are summarized in the
following 2X2 (read two by two) contingency table:
We would want to check whether being a man or a woman (columns) is independent of
having voted in the last election (rows). In other words, is “gender and voting independent”?

In [62]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math
import numpy as np 
import pandas as pd 
voter = {'men': ['2792','1486'],
        'women':['3591','2131']
        }
df = pd.DataFrame(voter, columns = ['men','women'], index = ['voted','notvoted'])
print(df)

#H0: gender and voting is independent, H1: gender and voting is not independent

dof = (2-1)*(2-1)

table = [[2792 , 3591] , [1486, 2131]]

stat, p, dof, expected = chi2_contingency(table)

print("\nexpected values",expected)
print("\ntest statistics", (round(stat,4)))

critical = chi2.ppf(.95, 1)
print("\n",(round(critical,4)))
print("Since test statistics is greater than the critical value ,\nwe reject the null hypothesis, and gender and voting are not independent")


           men women
voted     2792  3591
notvoted  1486  2131

expected values [[2730.6474 3652.3526]
 [1547.3526 2069.6474]]

test statistics 6.5523

 3.8415
Since test statistics is greater than the critical value ,
we reject the null hypothesis, and gender and voting are not independent


Problem Statement 19:
A sample of 100 voters are asked which of four candidates they would vote for in an
election. The number supporting each candidate is given below:
Do the data suggest that all candidates are equally popular? [Chi-Square = 14.96,
with 3 df, 𝑝 0.05 .

In [64]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math

chi_square  = 14.96
df = 3
#p = 0.05
critical = chi2.ppf(.95, 3)
print((round(critical,4)))
print("Calculated value of chi square:", 
      (round(chi_square,4)), "is more than the tabulated value ",
      (round(critical,4)), "therfore we reject the null hypothesis, \nand conclude all candidates are not equally popular")
#pvalue at 0.05 and chi_square

p_val = chi2.pdf(14.96 , 3)
print((round(p_val,4)),"since the p value is less than the 5% level of significance , \nwe reject the null hypothesis, and conclude all candidates are not equally popular")

7.8147
Calculated value of chi square: 14.96 is more than the tabulated value  7.8147 therfore we reject the null hypothesis, 
and conclude all candidates are not equally popular
0.0009 since the p value is less than the 5% level of significance , 
we reject the null hypothesis, and conclude all candidates are not equally popular


Problem Statement 20:
Children of three ages are asked to indicate their preference for three photographs of
adults. Do the data suggest that there is a significant relationship between age and
photograph preference? What is wrong with this study? [Chi-Square = 29.6, with 4
df: 𝑝 < 0.05].

In [102]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math
import numpy as np 
import pandas as pd 

In [153]:
#H0: There is significant relationship between age and photograph preference
#H1: There is no significant relationship between age and photograph preference

data = {'A':['18','2','20'],
        'B':['22','28','10'],
        'C':['20','40','40'] ,      
        }
df = pd.DataFrame(data, columns = ['A','B','C'], index = ['5-6 years','7-8 years','9-10 years'])
print(df)

dof = (3-1)*(3-1)

table = [[18 , 2,20],[22,28,10],[20,40,40]]

stat, p, dof, expected = chi2_contingency(table)

print("\n Expected values\n",expected)
print("\nchi square calculated", stat)

chi_square_tabulated = chi2.ppf(.95,4)
print("\nchisquare tabulated", chi_square_tabulated)
p_value = 1-chi2.cdf(x=29.6,df = dof)
print((round(p_value,4)))
print('''\nchi square calculated is greater than chi square tabulated so we retain the null hypothesis,
      \ni,e There is significant relationship between age and photograph preference.''')
      
      

             A   B   C
5-6 years   18  22  20
7-8 years    2  28  40
9-10 years  20  10  40

 Expected values
 [[12. 14. 14.]
 [18. 21. 21.]
 [30. 35. 35.]]

chi square calculated 29.603174603174605

chisquare tabulated 9.487729036781154
0.0

chi square calculated is greater than chi square tabulated so we retain the null hypothesis,
      
i,e There is significant relationship between age and photograph preference.


Problem Statement 21:
A study of conformity using the Asch paradigm involved two conditions: one where
one confederate supported the true judgement and another where no confederate
gave the correct response.
Is there a significant difference between the "support" and "no support" conditions in the
frequency with which individuals are likely to conform? [Chi-Square = 19.87, with 1 df:
𝑝 < 0.05].

In [97]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math
import numpy as np 
import pandas as pd 

#H0: There is no relationship between support and no support conditions 
#H1: There is relationship between support and no support conditions 

data = {'Support':['18','32'],
        'No Support':['40','10'],
        }
df = pd.DataFrame(data, columns = ['Support','No Support'], index = ['Confirm','Not Confirm'])
print(df)

dof = (2-1)*(2-1)

table = [[18 , 32],[40,10]]

stat, p, dof,expected = chi2_contingency(table)
print("\nExpected values\n",expected)

print("\nChi square calculated\n",(round(stat,4)))
#print(p)
critical = chi2.ppf(0.95, 1)
print("\nchi square tabulated",(round(critical,4)))
print('''\nGiven that p<0.05 , Therefore we reject H0,
      i,e. There is relationship between support and no support conditions 
''')

            Support No Support
Confirm          18         40
Not Confirm      32         10

Expected values
 [[29. 21.]
 [29. 21.]]

Chi square calculated
 18.1034

chi square tabulated 3.8415

Given that p<0.05 , Therefore we reject H0,
      i,e. There is relationship between support and no support conditions 



Problem Statement 22:
We want to test whether short people differ with respect to their leadership qualities
(Genghis Khan, Adolf Hitler and Napoleon were all stature-deprived, and how many midget
MP's are there?) The following table shows the frequencies with which 43 short people and
52 tall people were categorized as "leaders", "followers" or as "unclassifiable". Is there a
relationship between height and leadership qualities?
[Chi-Square = 10.71, with 2 df: 𝑝 < 0.01].

In [72]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math
import numpy as np 
import pandas as pd 

#H0: height and leadership quality are independent
#H1: height and leadership qualities are not independent

data = {'Short':['12','22','9'],
        'Tall':['32','14','6']
        }
df = pd.DataFrame(data, columns = ['Short','Tall'], index = ['Leader','Follower','unclassifiabl'])
print(df)

dof = (3-1)*(2-1)

table = [[12 , 22, 9] , [32,14,6]]

stat, p, dof, expected = chi2_contingency(table)
print("\nExpected Values\n",expected)
print("\nchi square calculated",(round(stat,4)))
critical = chi2.ppf(.99, 2)
print("\nchi square tabulated",(round(critical,4)))
print("\nsince the chi square calculated is greater than the tabulated value, \nwe reject the null hypothesis. \nAnd conclude that the height and leadership are not independent")


              Short Tall
Leader           12   32
Follower         22   14
unclassifiabl     9    6

Expected Values
 [[19.91578947 16.29473684  6.78947368]
 [24.08421053 19.70526316  8.21052632]]

chi square calculated 10.7122

chi square tabulated 9.2103

since the chi square calculated is greater than the tabulated value, 
we reject the null hypothesis. 
And conclude that the height and leadership are not independent


Problem Statement 23:
Each respondent in the Current Population Survey of March 1993 was classified as
employed, unemployed, or outside the labor force. The results for men in California age 35-
44 can be cross-tabulated by marital status, as follows 
Men of different marital status seem to have different distributions of labor force status. Or is
this just chance variation? (you may assume the table results from a simple random
sample.)

In [75]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
import math
import numpy as np 
import pandas as pd 

#H0: the distribution of labour force is same for different marital status
#H1: the distribution of labour force is not same for different marital status

data = {'Married':['679','63','42'],
        'Widow':['103','10','18'],
        'Never Married':['114','20','25']
        }
df = pd.DataFrame(data, columns = ['Married','Widow','Never Married'], index = ['Employed','Unemployed','Not in Labour force'])
print(df)

dof = (3-1)*(3-1)

table = [[679,63,42] , [103,10,18],[114,20,25]]
stat, p, dof, expected = chi2_contingency(table)
print("\nExpected values:\n", expected)
print("\nChisquare_calculated:",(round(stat,4)))

chi_square_tabulated = chi2.ppf(0.95,4)
print("\nChi_square tabulated:",(round(chi_square_tabulated,4)))
print("\nSince the chi squate calculated is greater than tabulated value we reject the null hypothesis")


                    Married Widow Never Married
Employed                679   103           114
Unemployed               63    10            20
Not in Labour force      42    18            25

Expected values:
 [[654.06331471  67.88826816  62.04841713]
 [109.2886406   11.34357542  10.36778399]
 [132.64804469  13.76815642  12.58379888]]

Chisquare_calculated: 31.6131

Chi_square tabulated: 9.4877

Since the chi squate calculated is greater than tabulated value we reject the null hypothesis
